angular.module(
    'de.cismet.todoApp',
    [
        'ngResource',
        'de.cismet.todoApp.controllers',
        'de.cismet.todoApp.directives',
        'de.cismet.todoApp.filters',
        'de.cismet.todoApp.services',
    ]
);